FROM tomcat:9-jdk8

COPY ./docker/spring-instrument-4.3.3.RELEASE.jar /usr/local/tomcat/lib
COPY ./docker/aspectjweaver-1.8.9.jar /usr/local/tomcat/lib

# TODO: Script artifact name
COPY build/libs/spring4-mvc-gradle-xml-hello-world.war /usr/local/tomcat/webapps/spring4.war
